CREATE USER WSSAUTHCXN1 IDENTIFIED BY WSSAUTHCXN1 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
ALTER USER WSSAUTHCXN1 QUOTA UNLIMITED ON USERS;
GRANT "DBA" TO WSSAUTHCXN1;
 
CREATE USER WSSCLOTHINGCXN1 IDENTIFIED BY WSSCLOTHINGCXN1 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
ALTER USER WSSCLOTHINGCXN1 QUOTA UNLIMITED ON USERS;
GRANT "DBA" TO WSSCLOTHINGCXN1;

CREATE USER WSSPICTURESCXN1 IDENTIFIED BY WSSPICTURESCXN1 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
ALTER USER WSSPICTURESCXN1 QUOTA UNLIMITED ON USERS;
GRANT "DBA" TO WSSPICTURESCXN1;