CREATE USER WSSAUTHCXN1 IDENTIFIED BY WSSAUTHCXN1 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
ALTER USER WSSAUTHCXN1 QUOTA UNLIMITED ON USERS;
GRANT "DBA" TO WSSAUTHCXN1;
 
CREATE USER WSSGARMENTCXN1 IDENTIFIED BY WSSGARMENTCXN1 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
ALTER USER WSSGARMENTCXN1 QUOTA UNLIMITED ON USERS;
GRANT "DBA" TO WSSGARMENTCXN1;